Grails 7: Update test Docker image to Java 17
Changed openjdk-11-jdk to openjdk-17-jdk in test/docker/dockers/rundeck/Dockerfile.

Fixes CI/CD integration test failure:
  java.lang.UnsupportedClassVersionError: class file version 61.0
  (Spring Boot 3 WAR requires Java 17, Docker image was using Java 11)

Test: T Integration SSL